apiVersion: v1
kind: Pod
metadata:
  labels:
    app: shorturl-pod
  name: shorturl-pod
spec:
  containers:
  - name: redis
    image: shorturl/redis:local
    env:
    - name: REDIS_PORT
      value: "6379"
    - name: BIND_IP
      value: "0"

  - name: worker
    image: shorturl/worker:local
    env:
    - name: APP_URL
      value: "localhost:8080"
    - name: APP_PORT
      value: "5500"
    - name: REDIS_PORT
      value: "6379"
    ports:
    - containerPort: 5500
      hostPort: 8080
      protocol: TCP

  restartPolicy: Always
